export const USER_INFO = 'USER_INFO';

export const SIDE_EFFECT_INFO = 'SIDE_EFFECT_INFO';

export const USER_CHOICE = 'USER_CHOICE';

export const INTERESTED_TREATMENT = 'INTERESTED_TREATMENT';

export const CURRENT_TREATMENT = 'CURRENT_TREATMENT';

export const PREVIOUS_TREATMENT = 'PREVIOUS_TREATMENT';

export const SUFFERED_SYMPTOMS = 'SUFFERED_SYMPTOMS';

export const MEDICAL_RESULTS = 'MEDICAL_RESULTS';

export const TRIAL_RESULTS = 'TRIAL_RESULTS'