export const USER_INFO = 'USER_INFO';

export const USER_CHOICE = 'USER_CHOICE';

export const INTERESTED_TREATMENT = 'INTERESTED_TREATMENT';

export const CURRENT_TREATMENT = 'CURRENT_TREATMENT';

export const PREVIOUS_TREATMENT = 'PREVIOUS_TREATMENT';