export const USER_INFO = 'USER_INFO';

export const SIDE_EFFECT_INFO = 'SIDE_EFFECT_INFO';

export const USER_CHOICE = 'USER_CHOICE';

export const INTERESTED_TREATMENT = 'INTERESTED_TREATMENT';

export const CURRENT_TREATMENT = 'CURRENT_TREATMENT';

export const PREVIOUS_TREATMENT = 'PREVIOUS_TREATMENT';

export const SUFFERED_SYMPTOMS = 'SUFFERED_SYMPTOMS';

export const TREATMENT_RESULTS = 'TREATMENT_RESULTS';

export const TRIAL_RESULTS = 'TRIAL_RESULTS';

export const STEP_COUNT = 'STEP_COUNT';

export const USER_ABOUT = 'USER_ABOUT';

export const USER_LIFE = 'USER_LIFE';

export const USER_FAMILY = 'USER_FAMILY';

export const USER_MEDS = 'USER_MEDS';

export const USER_SURGERY = 'USER_SURGERY';

export const USER_MOTORSY = 'USER_MOTORSY';

export const USER_NONMOTORSY = 'USER_NONMOTORSY';